### ISSUE TITLE
Unrecognized function or variable 'try_12_d1_d2'

### ISSUE THREAD

**Issue by imgemp** [zihangm/riemannian-streaming-cca#1]
Hi Zihang, thanks for open sourcing your code. As far as I can tell, I've followed the instructions, but I don't see the function `try_12_d1_d2` defined anywhere. Matlab throws an error when I try to run `demo_run`. Can you help resolve this?

**Comment by zihangm** [comment]
Hi, thanks for bringing this up. 'try_12_d1_d2' should be changed to "RSG_plus" and I have updated the repo. sorry for the confusion.

**Comment by imgemp** [comment]
No worries. Thanks for the prompt response!
